"""
Build the dashboard's halal data file from the fundamentals cache.

demo.html is a static, no-backend file you open with `open demo.html` (file://). Over
file:// browsers block fetch(), so we can't load JSON — instead we emit a JS file that
assigns `window.HALAL_DASH`, included via <script src="halal_data.js">. The dashboard
prefers that global and falls back to a small embedded slice if the file is absent.

This screens EVERY cached ticker (current tier + ratios + purification) and emits each
one's 8-year point-in-time tier timeline — so the in-page lookup covers the full universe,
not a hand-picked subset, and never drifts from the Python screen (same classify engine).

    python -m scripts.build_halal_dashboard_data        # writes halal_data.js next to demo.html
"""
import json
from pathlib import Path

from src.fundamentals import _load
from src.halal_screen import screen_cached
from src.halal_history import tier_timeline
from src.tier_monitor import diff_tiers, SNAPSHOT_PATH

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "halal_data.js"


def build() -> dict:
    cache = _load()
    data, history, asof = {}, {}, None
    cur = {}  # for the tier-change diff
    for ticker in sorted(cache):
        r = screen_cached(ticker, cache=cache)
        d, i = r["debt_to_assets"], r["interest_income_ratio"]
        data[ticker] = {
            "d": round(d * 100, 1) if d is not None else None,
            "i": round(i * 100, 1) if i is not None else None,
            "pur": round((r.get("purification_pct") or 0) * 100, 2),
            # citation posture — carried so the dashboard can show "verified-on + source"
            "src": r.get("source"),
            "asof": r.get("as_of"),
            "stale": bool(r.get("stale")),
        }
        history[ticker] = [{"y": row["year"], "t": row["tier"]}
                           for row in tier_timeline(ticker, cache=cache) if row["year"]]
        cur[ticker] = {"tier": r["tier"], "debt_to_assets": d, "interest_income_ratio": i}
        asof = asof or r.get("as_of")

    # Tier-change alerts: read-only diff vs the last saved snapshot (don't advance it here —
    # that's tier_monitor's job on the quarterly refresh). Surfaces 🟢→🔴 transitions.
    try:
        old = json.loads(SNAPSHOT_PATH.read_text())
    except Exception:
        old = {}
    alerts = diff_tiers(old, cur) if old else []

    # Screening-health summary ("who screens the screener" — make freshness visible)
    stale_n = sum(1 for v in data.values() if v["stale"])
    health = {"screened": len(data), "stale": stale_n,
              "fresh_pct": round((len(data) - stale_n) / len(data) * 100) if data else 0}

    return {"asof": asof, "n": len(data), "data": data, "history": history,
            "alerts": alerts, "health": health}


def main():
    payload = build()
    OUT.write_text(
        "/* AUTO-GENERATED by scripts/build_halal_dashboard_data.py — do not edit by hand. */\n"
        f"window.HALAL_DASH = {json.dumps(payload, ensure_ascii=False, separators=(',', ':'))};\n"
    )
    print(f"wrote {OUT.relative_to(ROOT)} — {payload['n']} tickers, as of {payload['asof']}")


if __name__ == "__main__":
    main()
